presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.14.3
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "300m"
  # - name: thoth-mypy-py38  TODO: Fix mypy errors
  #   decorate: true
  #   skip_report: false
  #   always_run: true
  #   context: aicoe-ci/prow/mypy
  #   spec:
  #     containers:
  #       - image: quay.io/thoth-station/thoth-pytest-ubi8-py38:v0.13.0
  #         command:
  #           - "/usr/local/bin/mypy"
  #           - "thoth/python"
  #           - "--ignore-missing-imports"
  #         resources:
  #           requests:
  #             memory: "1Gi"
  #             cpu: "500m"
  #           limits:
  #             memory: "2Gi"
  #             cpu: "1"
